### ISSUE TITLE
Can not print from NC 23.0.6

### ISSUE THREAD

**Issue by FadeFx** [e-alfred/nextcloud-printer#20]
Hi, i have a NC 23.0.6 installation (NextcloudPi) on my RPi4 with Debian Bullseye base, i had printer app working before with my old installation on Buster where i moved my NC installation from, but on Bullseye i can not get it to work anymore, i can print a CUPS testpage, i have allowed www-data on the printer, but i think my actual problem is way before it comes to CUPS. the NC log shows this when i try to print:

```
Exception: Call to a member function getLocalFile() on null in file '/var/www/nextcloud/lib/private/Files/Filesystem.php' line 529
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()

Verursacht durch Error: Call to a member function getLocalFile() on null
/var/www/nextcloud/apps/printer/lib/Controller/PrinterController.php - line 42:

OC\Files\Filesystem::getLocalFile()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\Printer\Controller\PrinterController->printfile()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()
```

Printer app version is 0.0.5

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by FadeFx** [comment]
Problem fixed by:
https://github.com/e-alfred/nextcloud-printer/issues/16#issuecomment-1023773876

plus editing folder name in /var/www/nextcloud/apps/
