### ISSUE TITLE
empty Printer tab in details

### ISSUE THREAD

**Issue by mlmss** [e-alfred/nextcloud-printer#6]
I was using the printer app for a couple of weeks without problems. Just today I found out that all of a sudden the printer tab in details is empty. Everything was fine a week ago.
As far as I remember I've upgraded to 0.0.3 recently and Nextcloud to 18.0.5. I cannot recall what came first and whether it worked in between but a downgrade to 0.0.2 didn't help. 
I've tested sudo -u www-data lpr testfile.pdf and that works well.
Is there anything what I could do?

**Comment by e-alfred** [comment]
Nextcloud 18.0.5 has a nasty bug which breaks this app to, nothing I can do much about: https://github.com/nextcloud/server/issues/21239

**Comment by mlmss** [comment]
Thanks for pointing in the right direction. It did the trick. Meanwhile there is an update to 18.0.6 which solves the issue as well.
