### ISSUE TITLE
NC 18.0.5 Printer 0.0.3 Dropdown missing

### ISSUE THREAD

**Issue by FadeFx** [e-alfred/nextcloud-printer#8]
Hi, 
i dont exactly know when it happened, abut i have two instances of Nextcloud 18.0.5, one had the printer app working, one is a fresh install of Nextcloud and on both the dropdown for Portrait/Landscape selection is missing in the Details/Printer dialog, so the app is actually unusable.
![image](https://user-images.githubusercontent.com/41125748/85207665-a49d6c00-b32a-11ea-9ec8-d95f4df3a835.png)

**Comment by geostag** [comment]
I have exactly the same issue with the same Version Nextcloud 18.0.5.
cups is working on the commandline (lpstat -d, lpstat -p). The network (chrome developer tools) does not show any communication which appears to be related to the printer app when opening the Details Tab.
Any hints about how to debug?

**Comment by e-alfred** [comment]
Do you still encounter this problem on Nextcloud 19 or 20? Does the browser console show any errors?

**Comment by FadeFx** [comment]
No, i am now on nextcloud 20 and did a full reinstall on a new device (raspi4) and it all just works.
