### ISSUE TITLE
CUPS in Docker Container ?

### ISSUE THREAD

**Issue by malcomxcia** [e-alfred/nextcloud-printer#9]
Hello

I have Nextcloud in a docker container and CUPS in a container running.

I can print from the CUPS web interface but not through Nextcloud.

What am I doing wrong?

**Comment by Mailblocker** [comment]
Hi,
take a look at this [issue](https://github.com/e-alfred/nextcloud-printer/issues/5) or at my PR [here](https://github.com/e-alfred/nextcloud-printer/pull/7).

**Comment by malcomxcia** [comment]
Hallo ! ! !

Lieben Dank für deine Antwort, aber ich weis nicht was ich tun muss. Ich bin neu in der Docker und Linux Welt :-D

CUPS läuft auch in einem Docker Container.

**Comment by malcomxcia** [comment]
Hello ! ! !

Thanks for your answer, but I don't know what i must to do. I am new to the Docker and Linux World :-D

CUPS also runs in a Docker Container.

**Comment by malcomxcia** [comment]
Where do I have to save the startupscript and how can I call it at startup ?

**Comment by Mailblocker** [comment]
You don't have to save the startup script somewhere. You need to built a custom nextcloud container image including the startup script as described.

**Comment by e-alfred** [comment]
Should be fixed by https://github.com/e-alfred/nextcloud-printer/commit/6aff7406f35a744affb4c908f7069da5b59deb7f.
